---
title: "Categorical Lab"
author: "Randall Plyler"
date: "10/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("C:/Users/randa/Dropbox/Masters/Autumn/TBANLT 540 Applied Regression Analysis/Categorical Variables Lab"))
```


Library Packages

```{r library}

options(scipen=10000)
options(digits = 5)
library(readxl)
library(plyr)
library(tidyverse)
library(car)

```

Load Data

```{r load_data}

CatLotData <- read_excel("98312_Redfin_2021.xlsx")
View(CatLotData)
```

Select Subset


```{r}
CatLotData2 <- CatLotData %>% select(PRICE,BEDS, BATHS,`SQUARE FEET`,`LOT SIZE`,`YEAR BUILT`,`LOCATION`)
summary(CatLotData2)
show(CatLotData2)
```

Drop missing values

```{r}
CatLotData2 <-  CatLotData2[complete.cases(CatLotData2), ]
summary(CatLotData2)
```

Separate Lot Size into categories

```{r}
hist(CatLotData2$`LOT SIZE`)

CatLotData2$LotCat<-cut(CatLotData2$`LOT SIZE`, c(0,2500,5000,7500,10000,12500,15000,Inf))

View(CatLotData2)

```


Create factor variable for Neighborhoods, sort, and count

```{r}
CatLotData2$NeighCat<-factor(CatLotData2$LOCATION)
LocCount <- as.data.frame(table(CatLotData2$LOCATION))

summary(CatLotData2$NeighCat)
summary(CatLotData2$PRICE)

Prices<-aggregate(PRICE ~ NeighCat, CatLotData2, mean)

Prices[with(Prices, order(PRICE)),]

show(LocCount)
```

Recode the factor to collapse the categories >5 per category



```{r}




CatLotData3<-CatLotData2[!(CatLotData2$LOCATION=="Charleston" | CatLotData2$LOCATION=="Bremerton"),]


CatLotData3<-CatLotData2[!(CatLotData2$LOCATION=="Kitsap Lake" | CatLotData2$LOCATION=="West Bremerton"),]


summary(CatLotData2$NeighCat)
summary(CatLotData2$PRICE)


CatLotData3$NeighCat2 <- recode(CatLotData3$NeighCat, 'c("Kitsap Lake", "West Bremerton") = "West Bremerton"; c("Charleston", "Bremerton") = "Bremerton";')

View(CatLotData3)
summary(CatLotData3$NeighCat)
summary(CatLotData3$PRICE)


```



Check Prices again

```{r}
Prices2<-aggregate(PRICE ~ NeighCat2, CatLotData3, mean)

Prices2[with(Prices2, order(PRICE)),]

LocCount2 <- as.data.frame(table(CatLotData3$NeighCat2))

show(LocCount2)
```

Enforce ordering

```{r}
CatLotData3$NeighCat2<-factor(CatLotData3$NeighCat2,levels=c('West Bremerton', 'West Hills', 'Bremerton', 'Navy Yard City'))     # this is to enforce a order to the reference for the factor variable

summary(CatLotData3$NeighCat2) 

```


Regression with categorical variables

```{r}
CatFit1<-lm(PRICE~BATHS+BEDS+`SQUARE FEET`+LotCat+`YEAR BUILT`+ NeighCat2, data=CatLotData3)

summary(CatFit1)

```

Check for collinearity


```{r}
vif(CatFit1)
```


Partial F-tests

```{r}
CatFit2<-lm(PRICE~BATHS+`SQUARE FEET`+LotCat+`YEAR BUILT`+ NeighCat2, data=CatLotData2)

summary(CatFit2)
anova(CatFit1, CatFit2)

CatFit3<-lm(PRICE~BATHS+BEDS+`SQUARE FEET`+`YEAR BUILT`+ NeighCat2, data=CatLotData2)
summary(CatFit3)
anova(CatFit1,CatFit3)

CatFit4<-lm(PRICE~BATHS+BEDS+`SQUARE FEET`+`YEAR BUILT`+ LotCat, data=CatLotData2)
summary(CatFit4)
anova(CatFit1,CatFit4)

CatFit5<-lm(PRICE~BATHS+`SQUARE FEET`+`YEAR BUILT`+ LotCat+ NeighCat2, data=CatLotData2)
summary(CatFit5)

anova(CatFit1, CatFit5)

summary(CatFit1)
summary(CatFit5)


```


