---
title: "MSBA Group1"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("C:/Users/randa/Dropbox/Masters/Autumn/TBANLT 540 Applied Regression Analysis/MSBA Final"))
```


```{r, fig.width=10,fig.height=11}
library(readr)
library(tidyr)
library(dplyr)
library(readxl)
library(tidyverse)
library(ggplot2)

Annual_Salary_2010_thru_2013 <- read_csv("Annual_Salary_2010_thru_2013.csv")

Annual_Salary_2010_thru_2013_long <- Annual_Salary_2010_thru_2013 %>%
  pivot_longer(
    starts_with("Salary"), 
    names_to = "Year", 
    values_to = "Salary"
    ) 

Annual_Salary_2010_thru_2013_long_Clean <- Annual_Salary_2010_thru_2013_long %>%
  select(AgencyTitle,EmployeeName,JobTitle,Year,Salary) %>% mutate(Year=substring(Year,7,11))

Annual_Salary_Filtered <-Annual_Salary_2010_thru_2013_long_Clean[!(Annual_Salary_2010_thru_2013_long_Clean$Salary=="0"),]


#Filter for all schools
Annual_Salary_AllSchools <- Annual_Salary_Filtered[grepl("College",Annual_Salary_Filtered$AgencyTitle)| grepl("University",Annual_Salary_Filtered$AgencyTitle),]

#Exclude UW and WSU schools
Annual_Salary_AllSchools_Exclude_UW = Annual_Salary_AllSchools %>% filter(AgencyTitle != "University of Washington") 
Annual_Salary_AllSchools_Exclude_UW_WSU = Annual_Salary_AllSchools_Exclude_UW %>% filter(AgencyTitle != "Washington State University") 


#Map colleges to Congressional Districts
Annual_Salary_AllSchools$CongressionalDistrict <- recode(Annual_Salary_AllSchools$AgencyTitle,
  "Bates Technical College" = "Congressional District 6",
  "Bellevue Community College" = "Congressional District 9",
  "Bellingham Technical College" = "Congressional District 2",
  "Big Bend Community College" = "Congressional District 4",
  "Cascadia Community College" = "Congressional District 1",
  "Central Washington University" = "Congressional District 8",
  "Centralia College" = "Congressional District 3",
  "Clark College" = "Congressional District 3",
  "Clover Park Technical College" = "Congressional District 10",
  "Columbia Basin Community College" = "Congressional District 4",
  "Eastern Washington University" = "Congressional District 5",
  "Edmonds Community College" = "Congressional District 2",
  "Everett Community College" = "Congressional District 2",
  "Grays Harbor College" = "Congressional District 6",
  "Green River Community College" = "Congressional District 8",
  "Highline Community College" = "Congressional District 9",
  "Lake Washington Technical College" = "Congressional District 1",
  "Lower Columbia Community College" = "Congressional District 3",
  "Olympic College" = "Congressional District 6",
  "Peninsula Community College" = "Congressional District 6",
  "Pierce Community College" = "Congressional District 10",
  "Renton Technical College" = "Congressional District 9",
  "Seattle Community College" = "Congressional District 7",
  "Shoreline Community College" = "Congressional District 7",
  "Skagit Valley College" = "Congressional District 1",
  "South Puget Sound Community College" = "Congressional District 10",
  "Spokane Community College" = "Congressional District 5",
  "Tacoma Community College" = "Congressional District 6",
  "The Evergreen State College" = "Congressional District 10",
  "University of Washington" = "Congressional District 7",
  "Walla Walla Community College" = "Congressional District 5",
  "Washington State University" = "Congressional District 5",
  "Wenatchee Valley College" = "Congressional District 8",
  "Western Washington University" = "Congressional District 2",
  "Whatcom Community College" = "Congressional District 2",
  "Yakima Valley College" = "Congressional District 4"
)

```


```{r, fig.width=10,fig.height=11}
#creating a GGPLOT for visualization with Agency Title and Salary. Note this is preliminary and does not include congressional districts.
Annual_Salary_AllSchools_ggP2 <- ggplot(Annual_Salary_AllSchools, aes(x=AgencyTitle, y=Salary, colour=AgencyTitle)) + geom_point() + guides(fill=guide_legend(title=NULL + theme(axis.line = element_line(colour="black")) + xlim(0, 3000000) + theme(aspect.ratio = 2)))

Annual_Salary_AllSchools_ggP2 + scale_fill_discrete(guide=FALSE) + stat_smooth(method=loess, colour="black") +
 theme(legend.position="none") + theme(axis.text.x = element_text(angle=60, hjust=1),
 panel.grid.major.y = element_blank(),
 panel.grid.minor.y = element_blank(),
 panel.grid.major.x = element_line(colour="grey60", linetype="dashed"))

(Annual_Salary_AllSchools_ggP2)
```

```{r}


#create categorical variable
Annual_Salary_AllSchools$FactorVariable<-factor(Annual_Salary_AllSchools$CongressionalDistrict)
summary(Annual_Salary_AllSchools)
DistCong <- as.data.frame(table(Annual_Salary_AllSchools$FactorVariable))

#create ggplot w/ congressional districts as plot
Annual_Salary_AllSchools_ggP_WithFactor <- ggplot(Annual_Salary_AllSchools, aes(x=FactorVariable, y=Salary, colour=AgencyTitle)) + geom_point() + guides(fill=guide_legend(title=NULL + theme(axis.line = element_line(colour="black")) + xlim(0, 3000000) + theme(aspect.ratio = 2)))

Annual_Salary_AllSchools_ggP_WithFactor + stat_smooth(method=loess, colour="black") + scale_x_discrete(name = "Congressional Districts") +theme(legend.position="none") + theme(axis.text.x = element_text(angle=60, hjust=1),
 panel.grid.major.y = element_blank(),
 panel.grid.minor.y = element_blank(),
 panel.grid.major.x = element_line(colour="grey60", linetype="dashed"))


#Enforce ordering
Annual_Salary_AllSchools$CongressionalDistrictFactored<-factor(Annual_Salary_AllSchools$FactorVariable,levels=c('Congressional District 7', 'Congressional District 5', 'Congressional District 2', 'Congressional District 8', 'Congressional District 10', 'Congressional District 9', 'Congressional District 6', 'Congressional District 3', 'Congressional District 4', 'Congressional District 1'))

#year into date
Annual_Salary_AllSchools$Year <- as.Date(Annual_Salary_AllSchools$Year, format="%Y")
#write.csv(x=df3,file="df3.csv")

#First LM Model
LMModel_CongDist_AgencyTitle<-lm(Salary~ CongressionalDistrictFactored + AgencyTitle, data=Annual_Salary_AllSchools)
LMModel_CongDist<-lm(Salary~ CongressionalDistrictFactored, data=Annual_Salary_AllSchools)
LMModel_AgencyTitle<-lm(Salary~ AgencyTitle, data=Annual_Salary_AllSchools)

summary(LMModel_CongDist_AgencyTitle)
summary(LMModel_CongDist)
summary(LMModel_AgencyTitle)

#residuals
varA<-factor(Annual_Salary_AllSchools$Salary)
varA.residual<-residuals.lm(LMModel_CongDist_AgencyTitle)
ggplot(data=Annual_Salary_AllSchools, aes(x=CongressionalDistrictFactored, y=varA.residual))+geom_point()+theme(axis.text.x = element_text(angle=60, hjust=1))

```



